import {
  User,
  Subscriber,
  Household,
  Region,
  Complaint,
  Vehicle,
  Driver,
  Route,
  CHYM,
  Container,
  AppNotification,
  ServiceRating,
  SystemSettings,
  HousePolygon,
  GpsTrackSegment,
  StreetNetworkItem,
} from '../types';

export const initialUsers: User[] = [
  {
    id: 'usr-1',
    name: 'Dilshod Karimov',
    role: 'SUPER_ADMIN',
    email: 'admin@ecocontrol-navoiy.uz',
    phone: '+998 79 220 12 34',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    active: true,
  },
  {
    id: 'usr-2',
    name: 'Nargiza Alimova',
    role: 'RAHBARIYAT',
    email: 'boshliq@navoiy-tozahudud.uz',
    phone: '+998 90 987 65 43',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    active: true,
  },
  {
    id: 'usr-3',
    name: 'Sherzodbek Qodirov',
    role: 'DISPETCHER',
    email: 'dispetcher@navoiy-tozahudud.uz',
    phone: '+998 93 555 11 22',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    active: true,
  },
  {
    id: 'usr-4',
    name: 'Ulug‘bek Rustamov',
    role: 'HUDUD_MASULI',
    email: 'qiziltepa@tozamakon.eco',
    phone: '+998 97 700 88 99',
    regionId: 'reg-qzt',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    active: true,
  },
  {
    id: 'usr-5',
    name: 'Bekzod Tursunov',
    role: 'BRIGADA_MASULI',
    email: 'brigada1@navoiy-tozahudud.uz',
    phone: '+998 91 333 44 55',
    active: true,
  },
  {
    id: 'usr-6',
    name: 'Jasur Rahimov',
    role: 'HAYDOVCHI',
    email: 'jasur.driver@navoiy-tozahudud.uz',
    phone: '+998 94 444 77 88',
    vehicleId: 'veh-1',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
    active: true,
  },
  {
    id: 'usr-7',
    name: 'Aziza Madrahimova',
    role: 'ABONENT',
    email: 'aziza.resident@mail.uz',
    phone: '+998 90 321 00 11',
    regionId: 'reg-qzt',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    active: true,
  },
];

// 4 ta rasmiy Toza Hudud filiali (Tozamakon.eco tizimi bo'yicha)
export const initialRegions: Region[] = [
  {
    id: 'reg-tmd',
    name: 'Tomdi tumani',
    code: 'TMD',
    fullName: 'Tomdi t "Toza Hudud" DK - Томди тумани',
    inspectorName: 'Jalg‘as Ospanov',
    inspectorPhone: '+998 93 622 14 55',
    chymCount: 18,
    containersCount: 65,
    population: 16500,
    activeVehiclesCount: 4,
  },
  {
    id: 'reg-uchq',
    name: 'Uchquduq tumani',
    code: 'UCHQ',
    fullName: 'Uchquduq t "Toza Hudud" DK - Учкудук тумани',
    inspectorName: 'Qodir Yusupov',
    inspectorPhone: '+998 94 220 33 44',
    chymCount: 26,
    containersCount: 110,
    population: 38000,
    activeVehiclesCount: 6,
  },
  {
    id: 'reg-qzt',
    name: 'Qiziltepa tumani',
    code: 'QZT',
    fullName: 'Qiziltepa t "Toza Hudud" DK - Кизилтепа тумани',
    inspectorName: 'Farrux Saidov',
    inspectorPhone: '+998 93 111 22 33',
    chymCount: 32,
    containersCount: 130,
    population: 160000,
    activeVehiclesCount: 7,
  },
  {
    id: 'reg-zar',
    name: 'Zarafshon shahri',
    code: 'ZAR',
    fullName: 'Zarafshon sh "Toza Hudud" DK - Зарафшон шахар',
    inspectorName: 'Sanjar Ergashev',
    inspectorPhone: '+998 99 444 55 66',
    chymCount: 30,
    containersCount: 140,
    population: 86000,
    activeVehiclesCount: 6,
  },
];

// Chiqindi Yig‘ish Maydonchalari (ЧЙМ)
export const initialCHYMs: CHYM[] = [
  {
    id: 'chym-tmd-01',
    code: 'CHYM-TMD-01',
    name: 'Tomdibulog‘ MFY markaziy maydonchasi',
    address: 'Tomdi t., Tomdibulog‘ MFY, Markaziy ko‘cha',
    regionId: 'reg-tmd',
    regionName: 'Tomdi tumani',
    lat: 41.5656,
    lng: 64.6225,
    containerCount: 4,
    cameraStatus: 'ONLINE',
    cameraUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600',
    lastInspectionTime: 'Bugun 10:15',
    cleanlinessStatus: 'Yaxshi',
    fillPercentAvg: 60,
  },
  {
    id: 'chym-tmd-02',
    code: 'CHYM-TMD-02',
    name: 'Ayaqg‘ujum MFY maydonchasi',
    address: 'Tomdi t., Ayaqg‘ujum MFY',
    regionId: 'reg-tmd',
    regionName: 'Tomdi tumani',
    lat: 41.5510,
    lng: 64.6380,
    containerCount: 4,
    cameraStatus: 'ONLINE',
    cameraUrl: 'https://images.unsplash.com/photo-1595278069441-2cf29f8005a4?w=600',
    lastInspectionTime: 'Bugun 09:30',
    cleanlinessStatus: 'Yaxshi',
    fillPercentAvg: 45,
  },
  {
    id: 'chym-uchq-01',
    code: 'CHYM-UCHQ-01',
    name: 'Navro‘z MFY, Do‘stlik ko‘chasi maydonchasi',
    address: 'Uchquduq t., Navro‘z MFY, Do‘stlik ko‘chasi 8-uy',
    regionId: 'reg-uchq',
    regionName: 'Uchquduq tumani',
    lat: 42.1583,
    lng: 63.5572,
    containerCount: 5,
    cameraStatus: 'ONLINE',
    cameraUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600',
    lastInspectionTime: 'Bugun 10:30',
    cleanlinessStatus: 'Yaxshi',
    fillPercentAvg: 75,
  },
  {
    id: 'chym-uchq-02',
    code: 'CHYM-UCHQ-02',
    name: 'Konchilar MFY, Geologlar maydonchasi',
    address: 'Uchquduq t., Konchilar MFY, Geologlar ko‘chasi',
    regionId: 'reg-uchq',
    regionName: 'Uchquduq tumani',
    lat: 42.1640,
    lng: 63.5650,
    containerCount: 4,
    cameraStatus: 'ONLINE',
    cameraUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600',
    lastInspectionTime: 'Bugun 09:15',
    cleanlinessStatus: 'A’lo',
    fillPercentAvg: 40,
  },
  {
    id: 'chym-qzt-01',
    code: 'CHYM-QZT-01',
    name: 'Qiziltepa markazi, Bo‘ston MFY',
    address: 'Qiziltepa t., Bo‘ston MFY, Alisher Navoiy ko‘chasi',
    regionId: 'reg-qzt',
    regionName: 'Qiziltepa tumani',
    lat: 40.0331,
    lng: 64.8512,
    containerCount: 6,
    cameraStatus: 'ONLINE',
    cameraUrl: 'https://images.unsplash.com/photo-1595278069441-2cf29f8005a4?w=600',
    lastInspectionTime: 'Bugun 08:45',
    cleanlinessStatus: 'Yaxshi',
    fillPercentAvg: 70,
  },
  {
    id: 'chym-qzt-02',
    code: 'CHYM-QZT-02',
    name: 'Vang‘ozi MFY maydonchasi',
    address: 'Qiziltepa t., Vang‘ozi MFY',
    regionId: 'reg-qzt',
    regionName: 'Qiziltepa tumani',
    lat: 40.0450,
    lng: 64.8720,
    containerCount: 5,
    cameraStatus: 'ONLINE',
    cameraUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=600',
    lastInspectionTime: 'Bugun 10:00',
    cleanlinessStatus: 'Qoniqarsiz',
    fillPercentAvg: 95,
  },
  {
    id: 'chym-zar-01',
    code: 'CHYM-ZAR-01',
    name: '1-kichik nohiya, Konchilar maydonchasi',
    address: 'Zarafshon sh., 1-kichik nohiya, 14-uy oldi',
    regionId: 'reg-zar',
    regionName: 'Zarafshon shahri',
    lat: 41.5744,
    lng: 64.2014,
    containerCount: 5,
    cameraStatus: 'ONLINE',
    cameraUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600',
    lastInspectionTime: 'Bugun 09:40',
    cleanlinessStatus: 'Yaxshi',
    fillPercentAvg: 65,
  },
  {
    id: 'chym-zar-02',
    code: 'CHYM-ZAR-02',
    name: '3-kichik nohiya, Quruvchilar maydonchasi',
    address: 'Zarafshon sh., 3-kichik nohiya, 25-uy',
    regionId: 'reg-zar',
    regionName: 'Zarafshon shahri',
    lat: 41.5680,
    lng: 64.2150,
    containerCount: 4,
    cameraStatus: 'ONLINE',
    cameraUrl: 'https://images.unsplash.com/photo-1595278069441-2cf29f8005a4?w=600',
    lastInspectionTime: 'Bugun 10:10',
    cleanlinessStatus: 'A’lo',
    fillPercentAvg: 50,
  },
];

// Maxsus chiqindi tashuvchi texnikalar (85 - Navoiy viloyati)
export const initialVehicles: Vehicle[] = [
  {
    id: 'veh-1',
    plateNumber: '85 714 UZA',
    model: 'ISUZU NPR 75L (Kompaktor)',
    year: 2023,
    capacityM3: 10,
    capacityTons: 5.5,
    fuelType: 'Dizel',
    currentFuelPercent: 84,
    driverId: 'drv-1',
    driverName: 'Jasur Rahimov',
    gpsImei: '869402058192019',
    status: 'HARAKATDA',
    speedKmH: 32,
    lat: 40.0335,
    lng: 64.8515,
    heading: 90,
    lastUpdated: 'Hozirgina',
    currentRouteId: 'rt-1',
  },
  {
    id: 'veh-2',
    plateNumber: '85 820 BAA',
    model: 'MAN TGS 26.360',
    year: 2022,
    capacityM3: 18,
    capacityTons: 12.0,
    fuelType: 'Metan gaz',
    currentFuelPercent: 68,
    driverId: 'drv-2',
    driverName: 'Bobur Mirzayev',
    gpsImei: '869402058192020',
    status: 'HARAKATDA',
    speedKmH: 38,
    lat: 41.5745,
    lng: 64.2015,
    heading: 180,
    lastUpdated: '1 daqiqa oldin',
    currentRouteId: 'rt-2',
  },
  {
    id: 'veh-3',
    plateNumber: '85 930 VAA',
    model: 'KamAZ 53605 Ko-440',
    year: 2021,
    capacityM3: 16,
    capacityTons: 10.0,
    fuelType: 'Dizel',
    currentFuelPercent: 45,
    driverId: 'drv-3',
    driverName: 'Alisher Qosimov',
    gpsImei: '869402058192021',
    status: 'TO‘XTAGAN',
    speedKmH: 0,
    lat: 42.1585,
    lng: 63.5575,
    heading: 0,
    lastUpdated: '2 daqiqa oldin',
  },
  {
    id: 'veh-4',
    plateNumber: '85 450 EAA',
    model: 'ISUZU NQR 71 PL',
    year: 2024,
    capacityM3: 8,
    capacityTons: 4.5,
    fuelType: 'Dizel',
    currentFuelPercent: 92,
    driverId: 'drv-4',
    driverName: 'Temur Normatov',
    gpsImei: '869402058192022',
    status: 'HARAKATDA',
    speedKmH: 26,
    lat: 41.5658,
    lng: 64.6228,
    heading: 270,
    lastUpdated: 'Hozirgina',
  },
  {
    id: 'veh-5',
    plateNumber: '85 777 ZAA',
    model: 'MAN TGS 26.360',
    year: 2023,
    capacityM3: 20,
    capacityTons: 14.0,
    fuelType: 'Dizel',
    currentFuelPercent: 55,
    driverId: 'drv-5',
    driverName: 'Ravshan Xolmatov',
    gpsImei: '869402058192024',
    status: 'OFFLINE', // ALERT
    speedKmH: 0,
    lat: 40.0452,
    lng: 64.8725,
    heading: 0,
    lastUpdated: '2 soat oldin',
  },
];

export const initialDrivers: Driver[] = [
  {
    id: 'drv-1',
    fullName: 'Jasur Rahimov',
    phone: '+998 94 444 77 88',
    licenseNumber: 'AA 9845123',
    experienceYears: 7,
    vehicleId: 'veh-1',
    vehiclePlate: '85 714 UZA',
    rating: 4.9,
    status: 'Faol',
  },
  {
    id: 'drv-2',
    fullName: 'Bobur Mirzayev',
    phone: '+998 90 888 12 34',
    licenseNumber: 'AA 7412589',
    experienceYears: 10,
    vehicleId: 'veh-2',
    vehiclePlate: '85 820 BAA',
    rating: 4.8,
    status: 'Faol',
  },
  {
    id: 'drv-3',
    fullName: 'Alisher Qosimov',
    phone: '+998 91 999 44 22',
    licenseNumber: 'AB 6325418',
    experienceYears: 12,
    vehicleId: 'veh-3',
    vehiclePlate: '85 930 VAA',
    rating: 4.7,
    status: 'Faol',
  },
  {
    id: 'drv-4',
    fullName: 'Temur Normatov',
    phone: '+998 97 123 98 76',
    licenseNumber: 'AC 1254789',
    experienceYears: 5,
    vehicleId: 'veh-4',
    vehiclePlate: '85 450 EAA',
    rating: 4.9,
    status: 'Faol',
  },
  {
    id: 'drv-5',
    fullName: 'Ravshan Xolmatov',
    phone: '+998 90 555 77 99',
    licenseNumber: 'AE 8521473',
    experienceYears: 14,
    vehicleId: 'veh-5',
    vehiclePlate: '85 777 ZAA',
    rating: 4.5,
    status: 'Faol',
  },
];

// GPS MASHINA IZLARI (TREK) - 3 XIL RANGDA
// Yashil: < 24 soat (Bugun o'tgan)
// Sariq: 24 - 48 soat (1-2 kun oldin o'tgan)
// Qizil: > 48 soat (3+ kun oldin o'tgan / muddat o'tgan)
export const initialTrackSegments: GpsTrackSegment[] = [
  // 🟢 Yashil: Qiziltepa tumani Bo'ston MFY bo'ylab bugun ertalab o'tgan
  {
    id: 'trk-1',
    vehicleId: 'veh-1',
    vehiclePlate: '85 714 UZA',
    streetName: 'Qiziltepa t., Bo‘ston MFY, Alisher Navoiy ko‘chasi',
    path: [
      [40.0315, 64.8480],
      [40.0325, 64.8495],
      [40.0331, 64.8512],
      [40.0340, 64.8530],
    ],
    passedAt: 'Bugun 08:30',
    ageHours: 4,
    colorCategory: 'green',
  },
  // 🟢 Yashil: Zarafshon shahar 1-kichik nohiya
  {
    id: 'trk-2',
    vehicleId: 'veh-2',
    vehiclePlate: '85 820 BAA',
    streetName: 'Zarafshon sh., 1-kichik nohiya, Konchilar ko‘chasi',
    path: [
      [41.5720, 64.1980],
      [41.5732, 64.2000],
      [41.5744, 64.2014],
      [41.5755, 64.2030],
    ],
    passedAt: 'Bugun 09:45',
    ageHours: 3,
    colorCategory: 'green',
  },
  // 🟢 Yashil: Uchquduq tumani Do'stlik ko'chasi
  {
    id: 'trk-3',
    vehicleId: 'veh-3',
    vehiclePlate: '85 930 VAA',
    streetName: 'Uchquduq t., Navro‘z MFY, Do‘stlik ko‘chasi',
    path: [
      [42.1560, 63.5550],
      [42.1572, 63.5562],
      [42.1583, 63.5572],
      [42.1595, 63.5585],
    ],
    passedAt: 'Bugun 10:15',
    ageHours: 2,
    colorCategory: 'green',
  },
  // 🟡 Sariq: Tomdi tumani markaziy qatnov (Kecha o'tgan)
  {
    id: 'trk-4',
    vehicleId: 'veh-4',
    vehiclePlate: '85 450 EAA',
    streetName: 'Tomdi t., Tomdibulog‘ MFY, Markaziy ko‘cha',
    path: [
      [41.5630, 64.6200],
      [41.5645, 64.6212],
      [41.5656, 64.6225],
      [41.5670, 64.6240],
    ],
    passedAt: 'Kecha 11:20',
    ageHours: 26,
    colorCategory: 'yellow',
  },
  // 🔴 Qizil: Qiziltepa t. Vang'ozi chekka hudud (3 kundan ortiq o'tilmagan)
  {
    id: 'trk-5',
    vehicleId: 'veh-5',
    vehiclePlate: '85 777 ZAA',
    streetName: 'Qiziltepa t., Vang‘ozi MFY orqa mavze',
    path: [
      [40.0430, 64.8690],
      [40.0440, 64.8705],
      [40.0450, 64.8720],
      [40.0460, 64.8740],
    ],
    passedAt: '3 kun oldin',
    ageHours: 74,
    colorCategory: 'red',
  },
];

// Ko‘chalar tarmog‘i (Toza xarita: sun'iy shakllarsiz)
export const initialStreetNetwork: StreetNetworkItem[] = [];

// Xonadonlar (Toza baza: operatorlar o'zlari qo'shishi uchun bo'sh)
export const initialHousePolygons: HousePolygon[] = [];


// Konteynerlar (4 ta tuman CHYM maydonchalariga biriktirilgan)
export const initialContainers: Container[] = [];
const wasteTypes: Container['wasteType'][] = ['Aralash', 'Plastmassa', 'Qog‘oz', 'Shisha', 'Organik'];

initialCHYMs.forEach((chym, cIndex) => {
  for (let i = 1; i <= chym.containerCount; i++) {
    const contId = `cnt-${chym.regionId.replace('reg-', '')}-${cIndex * 10 + i}`;
    const code = `KNT-${chym.code.replace('CHYM-', '')}-${String(i).padStart(2, '0')}`;
    const wasteType = wasteTypes[(i - 1) % wasteTypes.length];
    
    let fill = Math.round(((cIndex * 19 + i * 27) % 85) + 15);
    if (chym.fillPercentAvg === 100 && i <= 2) fill = 100;
    else if (chym.fillPercentAvg >= 85 && i === 1) fill = 92;

    let status: Container['status'] = 'Normal';
    if (fill === 100) status = 'To‘lgan';
    else if (fill >= 80) status = 'Xavfli';
    else if (fill >= 50) status = 'Ogohlantirish';

    initialContainers.push({
      id: contId,
      code,
      chymId: chym.id,
      chymName: chym.name,
      address: chym.address,
      regionId: chym.regionId,
      regionName: chym.regionName,
      fillLevel: fill,
      wasteType,
      status,
      lastUpdated: '2026-09-18 10:30',
      sensorBattery: Math.round(80 + ((i * 5) % 20)),
      lat: chym.lat + (i * 0.0001 - 0.0002),
      lng: chym.lng + (i * 0.00015 - 0.0003),
    });
  }
});

// 110+ Abonentlar (Tomdi, Uchquduq, Qiziltepa, Zarafshon bo'yicha)
const firstNames = ['Dilshod', 'Jasur', 'Bobur', 'Sardor', 'Ulug‘bek', 'Alisher', 'Sanjar', 'Otabek', 'Nodira', 'Malika', 'Feruza', 'Aziza', 'Zilola', 'Madina', 'Gulnoza', 'Kamola'];
const lastNames = ['Karimov', 'Rahimov', 'Mirzayev', 'Rustamov', 'Qosimov', 'Normatov', 'Xolmatov', 'Po‘latov', 'Ergashev', 'To‘rayeva', 'Nazarov', 'Valiyev', 'Sodiqov', 'Sobirov'];
const tozamakonStreets = ['Mustaqillik', 'Alisher Navoiy', 'Do‘stlik', 'Konchilar', 'Bo‘ston', 'Geologlar', 'Quruvchilar', 'Tomdibulog‘', 'Vang‘ozi', 'Istiqlol'];

export const initialSubscribers: Subscriber[] = [];
for (let i = 1; i <= 112; i++) {
  const fName = firstNames[i % firstNames.length];
  const lName = lastNames[(i * 2) % lastNames.length];
  const reg = initialRegions[i % initialRegions.length];
  const street = tozamakonStreets[(i * 3) % tozamakonStreets.length];
  const houseNum = String((i % 45) + 1);
  const isCompany = i % 14 === 0;
  const isDebtor = i % 9 === 0;

  initialSubscribers.push({
    id: `sub-${reg.code.toLowerCase()}-${i}`,
    code: `AB-${reg.code}-${String(1000 + i)}`,
    fullName: isCompany ? `MChJ "${reg.name} ${fName} Servis"` : `${lName} ${fName}`,
    phone: `+998 79 ${String(220 + (i * 3) % 70)} ${String(10 + (i * 5) % 89)} ${String(10 + (i * 7) % 89)}`,
    address: `${reg.name}, ${street} ko‘chasi, ${houseNum}-uy`,
    regionId: reg.id,
    regionName: reg.name,
    householdNumber: `${houseNum}-xonadon`,
    type: isCompany ? 'Yuridik shaxs' : 'Aholi',
    status: isDebtor ? 'Qarzdor' : i % 25 === 0 ? 'To‘xtatilgan' : 'Faol',
    registeredDate: `2024-0${(i % 9) + 1}-${String((i % 28) + 1).padStart(2, '0')}`,
    balance: isDebtor ? -(Math.round((i * 12000) % 75000) + 15000) : Math.round((i * 24000) % 110000),
    notes: isCompany ? 'Maxsus shartnoma № ' + (300 + i) : undefined,
  });
}

// 50+ Xonadonlar
export const initialHouseholds: Household[] = [];
for (let i = 1; i <= 55; i++) {
  const reg = initialRegions[i % initialRegions.length];
  const street = tozamakonStreets[(i * 2) % tozamakonStreets.length];
  const chym = initialCHYMs[i % initialCHYMs.length];
  const sub = initialSubscribers[i % initialSubscribers.length];
  const isMulti = i % 3 !== 0;

  initialHouseholds.push({
    id: `hh-${reg.code.toLowerCase()}-${i}`,
    code: `XON-${reg.code}-${String(500 + i)}`,
    address: `${reg.name}, ${street} ko‘chasi, ${Math.round((i % 30) + 1)}-uy`,
    regionId: reg.id,
    regionName: reg.name,
    residentsCount: (i % 5) + 3,
    subscriberId: sub.id,
    subscriberName: sub.fullName,
    chymId: chym.id,
    chymName: chym.name,
    type: isMulti ? 'Ko‘p qavatli' : 'Hovli',
  });
}

// Murojaatlar (Tomdi, Uchquduq, Qiziltepa, Zarafshon bo'yicha)
export const initialComplaints: Complaint[] = [
  {
    id: 'cmp-1',
    code: 'MUR-QZT-001',
    subscriberId: 'sub-qzt-3',
    subscriberName: 'Alisher Boboyev',
    phone: '+998 93 456 12 34',
    address: 'Qiziltepa t., Vang‘ozi MFY',
    regionId: 'reg-qzt',
    regionName: 'Qiziltepa tumani',
    category: 'Konteyner to‘lib ketgan',
    description: 'Chiqindi idishlari to‘lib ketgan, Vang‘ozi MFYga maxsus texnika tezroq kelishi so‘raladi.',
    photoUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600',
    createdAt: '2026-09-18 08:24',
    status: 'Yangi',
    priority: 'Shoshilinch',
  },
  {
    id: 'cmp-2',
    code: 'MUR-ZAR-001',
    subscriberId: 'sub-zar-8',
    subscriberName: 'Sanjar Po‘latov',
    phone: '+998 93 222 11 00',
    address: 'Zarafshon sh., 3-kichik nohiya, 25-uy',
    regionId: 'reg-zar',
    regionName: 'Zarafshon shahri',
    category: 'Chiqindi o‘z vaqtida olinmadi',
    description: 'Grafik bo‘yicha har 2 kunda olinishi kerak edi, kechikish mavjud.',
    createdAt: '2026-09-18 09:15',
    status: 'Qabul qilindi',
    assignedStaffId: 'usr-3',
    assignedStaffName: 'Sherzodbek Qodirov (Dispetcher)',
    priority: 'Yuqori',
  },
  {
    id: 'cmp-3',
    code: 'MUR-UCHQ-001',
    subscriberId: 'sub-uchq-14',
    subscriberName: 'Feruza Ergasheva',
    phone: '+998 97 789 65 43',
    address: 'Uchquduq t., Navro‘z MFY, Do‘stlik ko‘chasi',
    regionId: 'reg-uchq',
    regionName: 'Uchquduq tumani',
    category: 'Maydoncha ifloslangan',
    description: 'Konteynerlar bo‘shatilgan, ammo atrofi supurilmagan.',
    createdAt: '2026-09-18 10:05',
    status: 'Mas’ulga biriktirildi',
    assignedStaffId: 'drv-3',
    assignedStaffName: 'Alisher Qosimov (Haydovchi)',
    priority: 'O‘rta',
  },
  {
    id: 'cmp-4',
    code: 'MUR-TMD-001',
    subscriberId: 'sub-tmd-21',
    subscriberName: 'Jamshid Valiev',
    phone: '+998 99 888 77 66',
    address: 'Tomdi t., Tomdibulog‘ MFY, Markaziy ko‘cha',
    regionId: 'reg-tmd',
    regionName: 'Tomdi tumani',
    category: 'Boshqa',
    description: 'Konteyner qopqog‘i shikastlangan, ta’mirlash talab etiladi.',
    createdAt: '2026-09-18 10:40',
    status: 'Bajarildi',
    assignedStaffId: 'drv-4',
    assignedStaffName: 'Temur Normatov (Haydovchi)',
    responseNotes: 'Konteyner qopqog‘i sozlandi.',
    completedAt: '2026-09-18 11:20',
    priority: 'Past',
  },
];

// Marshrutlar
export const initialRoutes: Route[] = [
  {
    id: 'rt-1',
    code: 'MR-QZT-01',
    title: 'Qiziltepa t. Bo‘ston va Vang‘ozi tongi tozalash',
    regionId: 'reg-qzt',
    regionName: 'Qiziltepa tumani',
    vehicleId: 'veh-1',
    vehiclePlate: '85 714 UZA',
    driverId: 'drv-1',
    driverName: 'Jasur Rahimov',
    date: '2026-09-18',
    shift: 'Ertalabki (06:00 - 14:00)',
    status: 'Jarayonda',
    pointsCount: 2,
    completedPointsCount: 1,
    startedAt: '06:30',
    distanceKm: 18.5,
    estimatedDurationMin: 150,
    points: [
      {
        id: 'rp-1-1',
        chymId: 'chym-qzt-01',
        chymName: 'Qiziltepa markazi, Bo‘ston MFY',
        address: 'Qiziltepa t., Bo‘ston MFY, Alisher Navoiy ko‘chasi',
        lat: 40.0331,
        lng: 64.8512,
        order: 1,
        status: 'Tozalandi',
        visitedAt: '08:35',
        collectedVolumeM3: 5.2,
      },
      {
        id: 'rp-1-2',
        chymId: 'chym-qzt-02',
        chymName: 'Vang‘ozi MFY maydonchasi',
        address: 'Qiziltepa t., Vang‘ozi MFY',
        lat: 40.0450,
        lng: 64.8720,
        order: 2,
        status: 'Kutilmoqda',
      },
    ],
  },
  {
    id: 'rt-2',
    code: 'MR-ZAR-01',
    title: 'Zarafshon sh. 1 va 3-kichik nohiya tozalash',
    regionId: 'reg-zar',
    regionName: 'Zarafshon shahri',
    vehicleId: 'veh-2',
    vehiclePlate: '85 820 BAA',
    driverId: 'drv-2',
    driverName: 'Bobur Mirzayev',
    date: '2026-09-18',
    shift: 'Ertalabki (06:00 - 14:00)',
    status: 'Jarayonda',
    pointsCount: 2,
    completedPointsCount: 1,
    startedAt: '07:00',
    distanceKm: 14.2,
    estimatedDurationMin: 120,
    points: [
      {
        id: 'rp-2-1',
        chymId: 'chym-zar-01',
        chymName: '1-kichik nohiya, Konchilar maydonchasi',
        address: 'Zarafshon sh., 1-kichik nohiya, 14-uy oldi',
        lat: 41.5744,
        lng: 64.2014,
        order: 1,
        status: 'Tozalandi',
        visitedAt: '09:15',
        collectedVolumeM3: 4.5,
      },
      {
        id: 'rp-2-2',
        chymId: 'chym-zar-02',
        chymName: '3-kichik nohiya, Quruvchilar maydonchasi',
        address: 'Zarafshon sh., 3-kichik nohiya, 25-uy',
        lat: 41.5680,
        lng: 64.2150,
        order: 2,
        status: 'Kutilmoqda',
      },
    ],
  },
  {
    id: 'rt-3',
    code: 'MR-UCHQ-01',
    title: 'Uchquduq t. Navro‘z va Konchilar MFY tozalash',
    regionId: 'reg-uchq',
    regionName: 'Uchquduq tumani',
    vehicleId: 'veh-3',
    vehiclePlate: '85 930 VAA',
    driverId: 'drv-3',
    driverName: 'Alisher Qosimov',
    date: '2026-09-18',
    shift: 'Ertalabki (06:00 - 14:00)',
    status: 'Jarayonda',
    pointsCount: 2,
    completedPointsCount: 1,
    startedAt: '07:30',
    distanceKm: 16.0,
    estimatedDurationMin: 135,
    points: [
      {
        id: 'rp-3-1',
        chymId: 'chym-uchq-01',
        chymName: 'Navro‘z MFY, Do‘stlik ko‘chasi maydonchasi',
        address: 'Uchquduq t., Navro‘z MFY, Do‘stlik ko‘chasi 8-uy',
        lat: 42.1583,
        lng: 63.5572,
        order: 1,
        status: 'Tozalandi',
        visitedAt: '09:40',
        collectedVolumeM3: 4.8,
      },
      {
        id: 'rp-3-2',
        chymId: 'chym-uchq-02',
        chymName: 'Konchilar MFY, Geologlar maydonchasi',
        address: 'Uchquduq t., Konchilar MFY, Geologlar ko‘chasi',
        lat: 42.1640,
        lng: 63.5650,
        order: 2,
        status: 'Kutilmoqda',
      },
    ],
  },
  {
    id: 'rt-4',
    code: 'MR-TMD-01',
    title: 'Tomdi t. Tomdibulog‘ markaziy qatnov',
    regionId: 'reg-tmd',
    regionName: 'Tomdi tumani',
    vehicleId: 'veh-4',
    vehiclePlate: '85 450 EAA',
    driverId: 'drv-4',
    driverName: 'Temur Normatov',
    date: '2026-09-18',
    shift: 'Ertalabki (06:00 - 14:00)',
    status: 'Jarayonda',
    pointsCount: 2,
    completedPointsCount: 1,
    startedAt: '08:00',
    distanceKm: 12.5,
    estimatedDurationMin: 110,
    points: [
      {
        id: 'rp-4-1',
        chymId: 'chym-tmd-01',
        chymName: 'Tomdibulog‘ MFY markaziy maydonchasi',
        address: 'Tomdi t., Tomdibulog‘ MFY, Markaziy ko‘cha',
        lat: 41.5656,
        lng: 64.6225,
        order: 1,
        status: 'Tozalandi',
        visitedAt: '09:50',
        collectedVolumeM3: 3.8,
      },
      {
        id: 'rp-4-2',
        chymId: 'chym-tmd-02',
        chymName: 'Ayaqg‘ujum MFY maydonchasi',
        address: 'Tomdi t., Ayaqg‘ujum MFY',
        lat: 41.5510,
        lng: 64.6380,
        order: 2,
        status: 'Kutilmoqda',
      },
    ],
  },
];

// Bildirishnomalar
export const initialNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'Konteyner to‘lib qoldi (95%)',
    message: 'Qiziltepa t. Vang‘ozi MFY (CHYM-QZT-02) maydonchasidagi konteyner to‘ldi. Reys talab qilinadi!',
    type: 'container_full',
    level: 'danger',
    isRead: false,
    createdAt: '15 daqiqa oldin',
    linkModule: 'containers',
  },
  {
    id: 'notif-2',
    title: 'Maxsus texnika aloqadan uzildi',
    message: 'MAN TGS (85 777 ZAA) GPS serveriga signal yubormayapti. Haydovchi: Ravshan Xolmatov.',
    type: 'vehicle_offline',
    level: 'danger',
    isRead: false,
    createdAt: '45 daqiqa oldin',
    linkModule: 'gps',
    targetId: 'veh-5',
  },
  {
    id: 'notif-3',
    title: 'Yangi murojaat kelib tushdi',
    message: 'Qiziltepa t. Vang‘ozi MFY bo‘yicha aholi shikoyati qabul qilindi (#MUR-QZT-001).',
    type: 'new_complaint',
    level: 'info',
    isRead: false,
    createdAt: '1 soat oldin',
    linkModule: 'complaints',
  },
];

// Baholar
export const initialRatings: ServiceRating[] = [
  {
    id: 'rat-1',
    subscriberId: 'sub-qzt-01',
    subscriberName: 'Dilshod Karimov',
    phone: '+998 90 123 45 67',
    rating: 5,
    comment: 'Qiziltepa tumanida xizmat sifati ancha yaxshilandi. Har kuni ertalab soat 08:30 da aniq kelib tozalashadi.',
    tags: ['O‘z vaqtida', 'Toza va ozoda', 'Xushmuomala'],
    createdAt: '2026-09-18 09:10',
    driverName: 'Jasur Rahimov',
  },
  {
    id: 'rat-2',
    subscriberId: 'sub-zar-01',
    subscriberName: 'Nodira To‘rayeva',
    phone: '+998 91 333 88 99',
    rating: 5,
    comment: 'Zarafshon shahar 1-kichik nohiyada konteynerlar atrofi ham toza qilib ketildi. Rahmat!',
    tags: ['Toza va ozoda', 'O‘z vaqtida'],
    createdAt: '2026-09-18 10:20',
    driverName: 'Bobur Mirzayev',
  },
  {
    id: 'rat-3',
    subscriberId: 'sub-uchq-01',
    subscriberName: 'Alisher Boboyev',
    phone: '+998 93 456 12 34',
    rating: 4,
    comment: 'Uchquduq tumanida grafik bo‘yicha o‘z vaqtida olib chiqilmoqda.',
    tags: ['O‘z vaqtida'],
    createdAt: '2026-09-17 17:45',
  },
];

export const initialSettings: SystemSettings = {
  orgName: '“Toza Hudud” DUK — Navoiy viloyati boshqarmasi',
  hotline: '1157 / +998 79 220 12 34',
  gpsApiEndpoint: 'https://api.gps-navoiy.ecocontrol.uz/v1/telemetry',
  telegramBotToken: '7392184912:AAH9K12..._navoiy_bot',
  telegramChatId: '@ecocontrol_navoiy_alerts',
  rtspGatewayUrl: 'rtsp://cam.navoiy-tozahudud.uz:8554/live',
  smsApiUrl: 'https://notify.eskiz.uz/api/message/sms/send',
  smsApiKey: 'sk_live_navoiy_ecocontrol_8501',
  autoAlertThreshold: 80,
};
